config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'posts/index'

  resources :messages
  devise_for :users
  get 'comments/create'

  get 'comments/delete'

  get 'helper/index'

  resources :projects
  # root "projects#index"
  get "projects/index"
  post "projects/new" => "projects#new"
  get "projects/show/:project_id" => "projects#set_project"
  # post "projects/"
  post "projects/show/:project_id/comments/create" => "comments#create"
  post "projects/show/:project_id/comments/delete/:comment_id" => "comments#delete"
  
  post "projects/delete/:project_id" => "projects#destroy"
  
  post '/searches/search' => 'searches#search'     
  
  Rails.application.routes.draw do
  resources :profiles
    root "posts#index"
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = params[:user_id]
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:carrier, :main, :intro)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  debugger
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :이름 %></br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :경력 %><br>
    <%= f.text_field :carrier %>
  </div>
  <div class="field">
    <%= f.label :직업 %><br>
    <%= f.text_field :main %>
  </div>
  <div class="field">
    <%= f.label :자기소개 %><br>
    <%= f.text_area :intro %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Carrier</th>
      <th>Main</th>
      <th>Intro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.carrier %></td>
        <td><%= profile.main %></td>
        <td><%= profile.intro %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

 <div class="field">
    <%= f.label :이름, :class => "name" %><br />
    <%= f.email_field :name, :class => "name-box", autofocus: true %>
  </div>
<p>
  <strong>Carrier:</strong>
  <%= @profile.carrier %>
</p>

<p>
  <strong>Main:</strong>
  <%= @profile.main %>
</p>

<p>
  <strong>Intro:</strong>
  <%= @profile.intro %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>