config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'posts/index'

  resources :messages
  devise_for :users
  get 'comments/create'

  get 'comments/delete'

  get 'helper/index'

  resources :projects
  # root "projects#index"
  get "projects/index"
  post "projects/new" => "projects#new"
  get "projects/show/:project_id" => "projects#set_project"
  # post "projects/"
  post "projects/show/:project_id/comments/create" => "comments#create"
  post "projects/show/:project_id/comments/delete/:comment_id" => "comments#delete"
  
  post "projects/delete/:project_id" => "projects#destroy"
  
  post '/searches/search' => 'searches#search'     
  
  Rails.application.routes.draw do
  resources :profiles
    root "posts#index"
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
    mount_uploaders :photos, PhotoUploader
    has_many :comments, dependent: :destroy    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    # debugger
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      if params[:id]
        @project = Project.find(params[:id])
        @comments = Comment.where(project_id: params[:id])
      else
        @project = Project.find(params[:project_id])
        @comments = Comment.where(project_id: params[:project_id])
      end
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:pname, :pageType, :deadline, :skillType0, :skillType1, :skillType2, :pcontent, {photos: []})
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-6">
      <span><%= f.label :페이지이름 %></span></span><br>
      <%= f.text_field :pname, :class => 'tf-name input' %>
    </div>
    <div class="col-lg-6">
      <span><%= f.label :"페이지 종류" %></span><br>
      <%= f.radio_button(:pageType, "0") %>&nbsp;
      <%= label_tag(:radio_field, "개인블로그") %>
      &nbsp;&nbsp;&nbsp;
      <%= f.radio_button(:pageType, "1") %>&nbsp;
      <%= label_tag(:radio_field, "단체블로그") %>
      &nbsp;&nbsp;&nbsp;
      <%= f.radio_button(:pageType, "2") %>&nbsp;
      <%= label_tag(:radio_field, "스타트업") %>
      &nbsp;&nbsp;&nbsp;
      <%= f.radio_button(:pageType, "3") %>&nbsp;
      <%= label_tag(:radio_field, "기타") %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <span><%= f.label :기한 %></span><br>
      <%= f.date_field :deadline, :type => 'date', :value => Date.today.strftime("%Y-%m-%d"), :class => 'input' %>
    </div>
    <div class="col-lg-3 input-img">
      <span><%= f.label :"넣고 싶은 이미지" %></span><br>
      <div class="input-file">
        <%= f.file_field :photos, multiple: true, :class => "ff-img" %>
      </div>    
    </div>
    
    <div class="check_field col-lg-6">
      <span><%= f.label :"필요한 기술자" %></span><br>
      <%= check_box(:skillType0, "1") %>&nbsp; <%= f.label :"프론트앤드 개발자" %>&nbsp;&nbsp;&nbsp;
      <%= check_box(:skillType1, "1") %>&nbsp; <%= f.label :"백앤드 개발자 " %>&nbsp;&nbsp;&nbsp;
      <%= check_box(:skillType2, "1") %>&nbsp; <%= f.label :"디자이너" %>&nbsp;&nbsp;&nbsp;
    </div>
  </div>
    
  
  <div class="row">
    <div class="col-lg-12">
      <span><%= f.label :"기타 요구사항" %></span><br>
      <%= f.text_area :pcontent, :class => "ta-requirement input" %>
    </div>
  </div>
  
  <div class="actions"></span><br>
    <%= f.submit :"글쓰기", :class => "submit-button" %>
    <a href="/">
      <button class="cancel-button">취소</button>
    </a>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>등록된 프로젝트입니다</h1>

<table>
  <thead>
    <tr>
      <th>프로젝트 명</th>
      <th>지원기간</th>
      <th>마감기한</th>
      <th>예상금액</th>
      <th>진행상태</th>
      <th>내용</th>
      <th>필요한 기술 태그</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.pname %></td>
        <td><%= project.supportperiod %></td>
        <td><%= project.deadline %></td>
        <td><%= project.limitmoney %></td>
        <td><%= project.planstate %></td>
        <td><%= project.pcontent %></td>
        <td><%= project.ptag %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<section id="new-post">
    
    <div class="container bg-white">
        <header>
            <h2>프로젝트 작성하기</h2>
        </header>
        <hr>
        <%= render 'form' %>
    </div>
</section>

<script type="text/javascript">
    var height = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;
    var elm = document.getElementById('new-post');
    elm.style.height = height + 'px';
</script>

app/views/projects/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<div class="project-content-container">
<p>
  <strong>프로젝트 명</strong>
  <%= @project.pname %>
</p>

<p>
  <strong>페이지 종류</strong>
  <% if @project.pageType == "0" %>
    gg
  <% elsif @project.pageType == "1" %>
    bbb
  <% elsif @project.pageType == "2" %>
    ccc
  <% elsif @project.pageType == "2" %>
    aa
  <% end %>
</p>

<p>
  <strong>마감기간</strong>
  <%= @project.deadline %>
</p>

<p>
  <strong>필요한 기술자</strong>
  <% if @project.skillType0 == "1" %>
    프론트앤드 개발자
  <% elsif @project.skillType1 == "1"%>
    백앤드 개발자
  <% elsif @project.skillType2 == "1"%>
  디자이너
  <% end %>
</p>

<p>
  <strong>기타요구</strong>
  <%= @project.pcontent %>
</p>

<p>
  <strong>내용</strong>
  <%= @project.pcontent %>
</p>


<div>
<p>
  <strong>사진</strong>
</p>
<% @project.photos.each do | photo | %>
  <img src="<%= photo.thumb.url %>" />
<% end %>
</div>   

<hr>
<h3>댓글</h3>
<form action="/projects/show/<%= @project.id%>/comments/create" method="post" >
    <input type='text' name='input_comment'>
    <input type="submit">
</form>
<hr>
<% @comments.each do |comment|%>
    <p>
        <%= comment.content %> 
       <a href="/projects/show/<%= @project.id%>/comments/delete/<%= comment.id%>" data-method='post' data-confirm="이 댓글을 삭제하시겠습니까?">[x]</a>
    </p>
<% end %>
<hr>
<%= link_to '[목록으로가기]', projects_path %>
<%= link_to '[수정]', edit_project_path(@project) %>
<a href="/projects/delete/<%=@project.id%>" data-confirm="진짜로 삭제 하시겠어요?"data-method="post">[삭제]</a>

</div>